version: '3'

services:
  # mysql
  db:
    image: mysql:8.0.13
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - dbnet
    environment:
      - MYSQL_USER=linux_news
      - MYSQL_PASSWORD=c8f7ab2819fbeb5e47b5af7ed1a23638af0302dc
      - MYSQL_DATABASE=linuxnews
      # rand password
      - MYSQL_ROOT_PASSWORD=5f91a613a6188eca16583a618d84000961bb04af
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - /opt/linux_news/data/mysql:/var/lib/mysql
    restart: on-failure

  # redis
  redis:
    image: redis:latest
    hostname: redis
    networks:
      - cachenet
    restart: on-failure

  # django
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: ./start-django.sh
    environment:
      - DB_PASSWORD=c8f7ab2819fbeb5e47b5af7ed1a23638af0302dc
      - DB_ADDR=db
      - DB_NAME=linuxnews
      - REDIS_ADDR=redis
    volumes:
      - /var/log/linux_news:/home/pydj/log
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - dbnet
      - cachenet
    depends_on:
      - db

  # celery
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: celery
    networks:
      - dbnet
      - cachenet
    environment:
      - DB_PASSWORD=c8f7ab2819fbeb5e47b5af7ed1a23638af0302dc
      - DB_ADDR=db
      - DB_NAME=linuxnews
      - REDIS_ADDR=redis
    command: ./start-celery.sh
    volumes:
      - /var/log/linux_news:/home/pydj/log
    depends_on:
      - redis

networks:
    dbnet:
      driver: bridge

    cachenet:
      driver: bridge
