# Generated by Django 2.1.3 on 2018-12-03 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publish_time', models.DateTimeField()),
                ('summary', models.TextField()),
                ('link', models.URLField(unique=True)),
            ],
            options={
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='NewsOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=50, unique=True)),
                ('feed_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsOrigin')),
            ],
        ),
        migrations.AddField(
            model_name='newsentry',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsOrigin'),
        ),
        migrations.AddField(
            model_name='newsentry',
            name='tags',
            field=models.ManyToManyField(to='news.NewsTag'),
        ),
    ]
